<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RootNamespace>Crafts</RootNamespace>
    <UserSecretsId>718ff415-5768-4cc8-8bbb-c82af99c82c1</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <!--Denne dependency/pakke/library kan gøre ting mere læseligt, så fx Addhours(-2) bliver til "for to timer siden"-->
    <PackageReference Include="Humanizer" Version="2.7.9" />
  </ItemGroup>

</Project>
